const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const SIGN_IN_SUCCESSFUL = "SIGN_IN_SUCCESSFUL";
const SIGN_UP = "SIGN_UP";
const SIGN_UP_SUCCESSFUL = "SIGN_UP_SUCCESSFUL";
const HAS_ERROR = "HAS_ERROR";

const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";

const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";

export {
  SIGN_IN,
  SIGN_OUT,
  SIGN_IN_SUCCESSFUL,
  SIGN_UP,
  SIGN_UP_SUCCESSFUL,
  HAS_ERROR,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  SHOW_ALERT,
  HIDE_ALERT,
};
